### ISSUE TITLE
Example config file

### ISSUE THREAD

**Issue by dark668** [infoassure/autorun-logger-server#1]
Based on the documentation I've assumed that the configuration file should look like the following with colons separating items

database_server: 192.168.xxx.xxx
database_name: arl
database_user: postgres
database_password:
http_ip: 0.0.0.0
http_port:
debug: false
processor_threads: 0
archive_dir: /opt/arl/archive_dir
temp_dir: /opt/arl/temp_dir
summary_dir: /opt/arl/summary_dir
server_pem: /opt/arl/server.pem
server_key: /opt/arl/server.key

Its not clear if thats correct or not can you include an example or arl-server.config.sample file in the git repo?

**Comment by woanware** [comment]
There is a sample file in the repo, located here:

https://github.com/infoassure/autorun-logger-server/blob/master/source/src/info-assure/arl-server.config
