### ISSUE TITLE
Postgres account

### ISSUE THREAD

**Issue by dark668** [infoassure/autorun-logger-server#2]
is there any method to permit another specific user being configured other than postgres, I haven't tried yet but not sure if this will have an impact on the client service?

**Comment by woanware** [comment]
As long as you change the permissions on all of the DB objects then you can use another user e.g. an application specific one

**Comment by woanware** [comment]
I will add

**Comment by woanware** [comment]
The v1.0.2 release now includes a script to define the user/password/privs. The installation instructions have also been updated to explain the changes:

https://github.com/infoassure/autorun-logger-server/blob/master/documents/installation.md
